@startuml mappingResearchStudy


map "ContactPoint" as contact #back:AliceBlue;header:LightSkyBlue;line:blue {
    nom => name
    telecommunication => telecom
}

map "Group" as Group #back:TECHNOLOGY;header:LightGreen {
    identifiant => ?
    type => "Person"
    actual => "True"
    Effectif à recruter => quantity
    Critères => characteristic
    Age => characteristic
    Genre => characteristic
}

map "Characteristic" as characteristic #back:TECHNOLOGY;header:LightGreen {
    xx => code
    erer => value
    khkjh => exlude
}

map "Organization" as Organization #back:BUSINESS;header:Gold {
    identifiant =>
    nom => name
    adresse => Adresse
    
}

map "Location" as Location #back:MistyRose;header:Violet {
    identifiant =>
    type => "Person"
    actual => "True"
}

map "EssaisCliniques => ResearchStudy" as RS #back:AliceBlue;header:LightSkyBlue;line:blue {
    Identifiant => identifier
    Nom de l'essai => title 
    Statut de l'essai => status 
    Sujet concerné => condition
    Contact => contact
    Résumé de l'essai => description
    Date début de l'essai => period.start
    Lieux => site
    Participants => enrollment
    Promoteur => sponsor
}


RS::Lieux *-[#Violet,dashed,thickness=4]-> Location
RS::Participants *-[#LightGreen,dashed,thickness=4]-> Group 
RS::Promoteur *-[#Gold,dashed,thickness=4]-> Organization
RS::Contact -[#lightBlue,thickness=2]> contact

Group::Critères -left[#LightGreen,thickness=2]> characteristic
Group::Age -left[#LightGreen,thickness=2]> characteristic
Group::Genre -left[#LightGreen,thickness=2]> characteristic

@enduml
