@startuml vueGlobale

'Declaration des éléments
rectangle EssaiClinique {

    rectangle ResearchStudy #LightSkyBlue;line:Blue;line.bold;text:Black

    rectangle Organization #Gold;line:Gold;text:Black

    rectangle Location #Violet;line:Violet;text:Black

    rectangle Group #LightGreen;line:white;text:Black

}

'Liens entre éléments
ResearchStudy -[#LightGreen,dashed,thickness=4]-> Group : enrollment
ResearchStudy -[#Violet,dashed,thickness=4]-> Location : site
ResearchStudy -[#Gold,dashed,thickness=4]-> Organization : sponsor

@enduml