@startuml
set namespaceSeparator ?
hide circle
hide class fields

package IG #DDDDDD{

     package Profiles #DDDDDD{

        class ECLAIREGroup{

             Group.characteristic.code => [None..None]
             Group.characteristic.value[x] => [None..None]
             Group.characteristic.value[x]:valueCodeableConcept => [0..1]
        } 

        class ECLAIRELocation{

             Location.telecom.extension:eclaire-site-contact-name => <&plus>[0..1]
        } 

        class ECLAIREResearchStudy{

             ResearchStudy.extension:eclaire-review-date => <&plus>[0..1]
             ResearchStudy.extension:eclaire-approval-date => <&plus>[0..1]
             ResearchStudy.extension:eclaire-therapeutic-area => <&plus>[0..1]
             ResearchStudy.extension:eclaire-recruitment-period => <&plus>[0..1]
             ResearchStudy.extension:eclaire-recruitment-status => <&plus>[0..1]
             ResearchStudy.extension:eclaire-description-summary-r5 => <&plus>[0..1]
             ResearchStudy.extension:eclaire-description-summary-r5.value[x] => <&plus>[1..None]
             ResearchStudy.extension:eclaire-outcome-measure-r5 => <&plus>[0..*]
             ResearchStudy.extension:eclaire-associated-party-r5 => <&plus>[0..*]
             ResearchStudy.extension:eclaire-label-r5 => <&plus>[0..*]
             ResearchStudy.identifier => [None..None]
             ResearchStudy.identifier:idPrimary => [0..1]
             ResearchStudy.identifier:idPrimary.use => [1..None]
             ResearchStudy.identifier:idPrimary.period.start => [None..None]
             ResearchStudy.identifier:idSecondary => [0..*]
             ResearchStudy.identifier:idSecondary.use => [1..None]
             ResearchStudy.title => [None..None]
             ResearchStudy.status => [None..None]
             ResearchStudy.primaryPurposeType => [None..None]
             ResearchStudy.phase => [None..None]
             ResearchStudy.category => [None..None]
             ResearchStudy.condition => [None..None]
             ResearchStudy.condition:medDRACondition => [0..*]
             ResearchStudy.condition:medDRACondition.id => [None..None]
             ResearchStudy.condition:medDRACondition.coding.system => [None..None]
             ResearchStudy.condition:diseaseCondition => [0..*]
             ResearchStudy.condition:diseaseCondition.id => [None..None]
             ResearchStudy.condition:diseaseCondition.text => [1..None]
             ResearchStudy.contact => [None..None]
             ResearchStudy.contact.extension:eclaire-contact-type => <&plus>[0..1]
             ResearchStudy.contact.extension:eclaire-contact-address => <&plus>[0..1]
             ResearchStudy.contact.extension:eclaire-contact-affiliation => <&plus>[0..1]
             ResearchStudy.contact.extension:eclaire-contact-name => <&plus>[0..1]
             ResearchStudy.relatedArtifact => [None..None]
             ResearchStudy.location => [None..None]
             ResearchStudy.description => [None..None]
             ResearchStudy.enrollment => [None..None]
             ResearchStudy.period.end => [None..None]
             ResearchStudy.sponsor => [None..0]
             ResearchStudy.principalInvestigator => [None..0]
             ResearchStudy.site => [None..None]
             ResearchStudy.arm.extension:eclaire-arm-intervention => <&plus>[0..*]
         }

     }
     package extension #paleturquoise {

     ECLAIRELocation -[#black,dashed,thickness=2]-> ECLAIRESiteContactName
     ECLAIREResearchStudy -[#black,dashed,thickness=2]-> ECLAIREReviewDate
     ECLAIREResearchStudy -[#black,dashed,thickness=2]-> ECLAIREApprovalDate
     ECLAIREResearchStudy -[#black,dashed,thickness=2]-> ECLAIRETherapeuticArea
     ECLAIREResearchStudy -[#black,dashed,thickness=2]-> ECLAIRERecruitmentPeriod
     ECLAIREResearchStudy -[#black,dashed,thickness=2]-> ECLAIRERecruitmentStatus
     ECLAIREResearchStudy -[#black,dashed,thickness=2]-> ECLAIREoutcomeMeasureR5
     ECLAIREResearchStudy -[#black,dashed,thickness=2]-> ECLAIREassociatedPartyR5
     ECLAIREResearchStudy -[#black,dashed,thickness=2]-> ECLAIRELabelR5
     ECLAIREResearchStudy -[#black,dashed,thickness=2]-> ECLAIREContactType
     ECLAIREResearchStudy -[#black,dashed,thickness=2]-> ECLAIREContactAddress
     ECLAIREResearchStudy -[#black,dashed,thickness=2]-> ECLAIREContactAffiliation
     ECLAIREResearchStudy -[#black,dashed,thickness=2]-> ECLAIREContactName
     ECLAIREResearchStudy -[#black,dashed,thickness=2]-> ECLAIREArmIntervention

        class ECLAIREApprovalDate{

          Extension.extension => [None..0]
          Extension.url => [None..None]
          Extension.value[x] => [None..None]
        } 
        class ECLAIREArmIntervention{

          Extension.extension:name => [0..1]
          Extension.extension:name.extension => [None..0]
          Extension.extension:name.url => [None..None]
          Extension.extension:name.value[x] => [None..None]
          Extension.extension:description => [0..1]
          Extension.extension:description.extension => [None..0]
          Extension.extension:description.url => [None..None]
          Extension.extension:description.value[x] => [None..None]
          Extension.url => [None..None]
          Extension.value[x] => [None..0]
        } 
        class ECLAIREassociatedPartyR5{

          Extension.extension => [1..None]
          Extension.extension:name => [0..1]
          Extension.extension:name.extension => [None..0]
          Extension.extension:name.url => [None..None]
          Extension.extension:name.value[x] => [None..None]
          Extension.extension:role => [1..1]
          Extension.extension:role.extension => [None..0]
          Extension.extension:role.url => [None..None]
          Extension.extension:role.value[x] => [None..None]
          Extension.extension:period => [0..*]
          Extension.extension:period.extension => [None..0]
          Extension.extension:period.url => [None..None]
          Extension.extension:period.value[x] => [None..None]
          Extension.extension:classifier => [0..*]
          Extension.extension:classifier.extension => [None..0]
          Extension.extension:classifier.url => [None..None]
          Extension.extension:classifier.value[x] => [None..None]
          Extension.extension:party => [0..1]
          Extension.extension:party.extension => [None..0]
          Extension.extension:party.url => [None..None]
          Extension.extension:party.value[x] => [None..None]
          Extension.url => [None..None]
          Extension.value[x] => [None..0]
        } 
        class ECLAIREContactAddress{

          Extension.extension => [None..0]
          Extension.url => [None..None]
          Extension.value[x] => [None..None]
        } 
        class ECLAIREContactAffiliation{

          Extension.extension => [None..0]
          Extension.url => [None..None]
          Extension.value[x] => [None..None]
        } 
        class ECLAIREContactName{

          Extension.extension => [None..0]
          Extension.url => [None..None]
          Extension.value[x] => [None..None]
        } 
        class ECLAIREContactType{

          Extension.extension => [None..0]
          Extension.url => [None..None]
          Extension.value[x] => [None..None]
        } 
        class ECLAIRELabelR5{

          Extension.extension:type => [0..1]
          Extension.extension:type.extension => [None..0]
          Extension.extension:type.url => [None..None]
          Extension.extension:type.value[x] => [None..None]
          Extension.extension:value => [0..1]
          Extension.extension:value.extension => [None..0]
          Extension.extension:value.url => [None..None]
          Extension.extension:value.value[x] => [None..None]
          Extension.url => [None..None]
          Extension.value[x] => [None..0]
        } 
        class ECLAIREoutcomeMeasureR5{

          Extension.extension:name => [0..1]
          Extension.extension:name.extension => [None..0]
          Extension.extension:name.url => [None..None]
          Extension.extension:name.value[x] => [None..None]
          Extension.extension:type => [0..1]
          Extension.extension:type.extension => [None..0]
          Extension.extension:type.url => [None..None]
          Extension.extension:type.value[x] => [None..None]
          Extension.extension:description => [0..1]
          Extension.extension:description.extension => [None..0]
          Extension.extension:description.url => [None..None]
          Extension.extension:description.value[x] => [None..None]
          Extension.extension:reference => [0..1]
          Extension.extension:reference.extension => [None..0]
          Extension.extension:reference.url => [None..None]
          Extension.extension:reference.value[x] => [None..None]
          Extension.url => [None..None]
          Extension.value[x] => [None..0]
        } 
        class ECLAIRERecruitmentPeriod{

          Extension.extension => [None..0]
          Extension.url => [None..None]
          Extension.value[x] => [None..None]
        } 
        class ECLAIRERecruitmentStatus{

          Extension.extension => [None..0]
          Extension.url => [None..None]
          Extension.value[x] => [None..None]
        } 
        class ECLAIREReviewDate{

          Extension.extension => [None..0]
          Extension.url => [None..None]
          Extension.value[x] => [None..None]
        } 
        class ECLAIRESiteContactName{

          Extension.extension => [None..0]
          Extension.url => [None..None]
          Extension.value[x] => [None..None]
        } 
        class ECLAIRETherapeuticArea{

          Extension.extension => [None..0]
          Extension.url => [None..None]
          Extension.value[x] => [None..None]
         }
     }
     package valueset #PaleVioletRed{

        class EclaireStudyPartyRoleVS  

     ECLAIREassociatedPartyR5 -[#black,dotted,thickness=2]-> EclaireStudyPartyRoleVS

        class EclaireStudyPartyOrganizationTypeVS  

     ECLAIREassociatedPartyR5 -[#black,dotted,thickness=2]-> EclaireStudyPartyOrganizationTypeVS

        class EclaireTypeContactVS  

     ECLAIREContactType -[#black,dotted,thickness=2]-> EclaireTypeContactVS

        class EclaireGroupCharacteristicKindVS  

     ECLAIREGroup -[#black,dotted,thickness=2]-> EclaireGroupCharacteristicKindVS

        class EclaireStudyPopulationVS  

     ECLAIREGroup -[#black,dotted,thickness=2]-> EclaireStudyPopulationVS

        class EclaireStudyTitleTypetVS  

     ECLAIRELabelR5 -[#black,dotted,thickness=2]-> EclaireStudyTitleTypetVS

        class EclaireStudyOutcomeTypeVS  

     ECLAIREoutcomeMeasureR5 -[#black,dotted,thickness=2]-> EclaireStudyOutcomeTypeVS

        class EclaireStatusRecruitementVS  

     ECLAIRERecruitmentStatus -[#black,dotted,thickness=2]-> EclaireStatusRecruitementVS

        class EclaireStudyPhaseVS  

     ECLAIREResearchStudy -[#black,dotted,thickness=2]-> EclaireStudyPhaseVS

        class EclaireCategoryVS  

     ECLAIREResearchStudy -[#black,dotted,thickness=2]-> EclaireCategoryVS
       }

package "Ressources de base" #palegreen {

 class "Group" as  class03937134cedab9078be39a77ee3a48a0 

    class03937134cedab9078be39a77ee3a48a0 --> ECLAIREGroup

 class "Location" as  classce5bf551379459c1c61d2a204061c455 

    classce5bf551379459c1c61d2a204061c455 --> ECLAIRELocation

 class "ResearchStudy" as  class9b1969036d5277c87c566c7a48c0e9dd 

    class9b1969036d5277c87c566c7a48c0e9dd --> ECLAIREResearchStudy
}
@enduml